### PR TITLE
Minor changes at Front-end

### PR DESCRIPTION
**Pull request by candyam5522**
-fix loading News and Funding message problem when first go to Help page and go back to home page
-get rid of few hardcoded eureka-webapp urls

### CODE REVIEW

**Comment by arpost** [comment]
Looks fine except for the replacement of the help screen with the old JSP version. The new help page works for me. Did you encounter an issue with it?

**Comment by arpost** [comment]
Actually, I'm not sure the ../protected part of the relative URLs is needed. Those should already be in the protected directory.

**Comment by candyam5522** [comment]
To explain why I use the old JSP version for the Help page

Here is the fact:
1. The index.html itself only contains only the code for rendering the banner, the actual page is loaded by Angular via the following code:
    <div class="container container-big">
            <ui-view></ui-view>
    </div>

2. The Homepage's actual page is eureka->views->main->main.html, which is inserted via above <ui-view> into index.html, inside this main.html, jason files for News and Funding should be able to inserted via id="versionHistory" and id="support"

3. The Help page's actual page is eureka->help->main->main.html, which is inserted via above <ui-view> into index.html as well

4. Currently I write javascript code inside index.html to do the actual insertion for jason files for News and Funding
        window.eureka.index.setup(contextPath);
        window.eureka.index.writeSupport();
        window.eureka.index.writeVersionHistory();
index.html includes eureka.index.js which contains the above js functions.

Here is the problem:
When the homepage first time loaded, the js code is executed, when I click the Help button, the page is not reloaded, just the <ui-view> changes from views->main.html to help->main.html, which is correct, but when you click Eureka button again, and goes back to the home page, the homepage is not reloaded, only the main.html changes back, so the js code I put inside index.html will not re-executed.
The first thought is put js code inside views->main.html, but this won't work, because Angular does not support this. The purpose of Angular is to separate module, view, controller, the views->main.html is only the view, if I want to do anything dynamic, I need to put it inside a controller, as in I need to write a controller inside the module.js, simply put js code inside views->main.html will not be executed by Angular.

Here is the solution:
1. Simply way: change the Help page to the old jsp one, so when I click Help, and go back to index.html, the js code inside index.html will be executed again, so the News and Funding jason files can be re-inserted. This fix only is a 2 lines change. easy.(I chose this one for yesterday's fix)

2. Simply but ugly: do not use jason files to inserted those msg, write plain text inside views->main.html. This fix only needs copy and paste, but not good for maintainance.

3. The hardest, the best practice, but take time: actually implement the controller, this is the part that is currently missing, we now only have view( views->main.html), module(jason files), but no controller. I would love to do this because for long term this is the best way, but it gonna take some time, this is not a 2 line fix.

**Comment by candyam5522** [comment]
I will ../protected part of the relative URLs, and test it, if it does work, then I will remove it and push to Github

**Comment by arpost** [comment]
Regarding the support and news sections, It's worth writing the controller, otherwise we can't use any of the angular pages other than the main page.

**Comment by candyam5522** [comment]
Okay, I will write a controller for it.

**Comment by arpost** [comment]
Please put controller in a separate pull request. I wanted to get these changes in. Thanks.

**Comment by candyam5522** [comment]
OKAY, will do

**Pull request merged**
