### PR TITLE
Add Angular controller for News and Funding at homepage

### PR DESCRIPTION
**Pull request by candyam5522**

### CODE REVIEW

**Comment by arpost** [comment]
The eureka.homeController.js belongs in the eureka directory not the assets directory. The eureka directory is where the angularjs code goes. I think it will get autoloaded if you put it there. Please document in a comment what is happening that requires the vert-offset class (the ng-if="$first" stuff). Otherwise, it looks fine. Thanks.

**Comment by candyam5522** [comment]
I tried to put the js file in eureka->views folder, because this js is for homepage, so I think that is the right place, but gulpfile.js does not like it, build failed. Since the original eureka.index.js(js is for loading News and Funding only) was in the assets folder and it works, so I putted it over there. I will try to move it to eureka.
The vert-offset is for format, this is the original design about how version history looks like, I will put a comment over there.
Right now build failed because I change to hibernate5 on local, need to find a way to fix it before I make those changes.

**Comment by candyam5522** [comment]
Please review the new commits, and let me know if you have any questions

**Comment by arpost** [comment]
The server-side of these patches are ready to go. On the client side, will be ready with a couple of minor changes:
1) I'm pretty sure you don't need to add those lines to <packagingIncludes>. I don't see any entries there for any other content in the eureka-webapp/src/main/webapp/eureka directory.
2) I believe the new script tags in index.html are not needed. Those new js files should be getting pulled into eureka-webapp/src/main/webapp/build/app.js automatically, so you don't need to refer to each one separately.

**Comment by candyam5522** [comment]
Just pushed a new commit, please review

**Pull request merged**
